model:
  name: gat
  params:
    num_layers: 5
    emb_dim: 128
    feat_dim: 640
    drop_ratio: 0.2

data:
  feature_type: graph
  target: D-
  data_path: ./data/processed/graphs/data_D-.npy
  label_path: ./data/processed/graphs/label_D-.npy

training:
  train_mode: true
  batch_size: 32
  lr: 0.001
  epochs: 300
  weight_decay: 1.0e-4
  warmup: 50
  test_size: 0.2
  random_seed: 42
  load_checkpoint: ./results/checkpoints/GAT_D-.model.pth
  scheduler_t_max: 250
  scheduler_eta_min: 1.0e-6

output:
  save_dir: ./results
  model_name: GAT_D-
